collector-api-cursos:
    image: otel/opentelemetry-collector:latest
    container_name: collector-api-cursos
    volumes:
        - ./collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    networks:
        - api
        - monit
    depends_on:
        - loki-api-cursos

jaeger-api-cursos:
    image: jaegertracing/opentelemetry-all-in-one
    container-name: jaeger-api-cursos
    ports:
        - 16686:16686
    networks:
        - monit
    depends_on:
        - collector-api-cursos
