#create a folder called  collector to insert this file ==> mkdir collector

receivers:
    otlp:
        protocols:
            grpc:
            http:
exporters:
        jaeger:
            endpoint: jaeger-api-cursos:14250
            tls:
                insecure: true
service
    pipelines:
        traces:
            receivers: [otlp]
            exporters: [jaeger]
